// This file is auto-generated by @hey-api/openapi-ts

export const AdminUserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            format: 'email',
            title: 'Email'
        },
        full_name: {
            type: 'string',
            maxLength: 120,
            minLength: 1,
            title: 'Full Name'
        },
        password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Password'
        },
        role: {
            '$ref': '#/components/schemas/Role'
        },
        hospital_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Hospital Id'
        }
    },
    type: 'object',
    required: ['email', 'full_name', 'password', 'role'],
    title: 'AdminUserCreate',
    description: `Payload for \`\`POST /users/\`\` (admin-only — role is explicitly chosen).

Role constraints enforced in the service layer:
- \`\`SUPER_ADMIN\`\`    → can create any role; must supply \`\`hospital_id\`\` for
                       HOSPITAL_ADMIN and CLINICIAN.
- \`\`HOSPITAL_ADMIN\`\` → can only create \`\`CLINICIAN\`\`; \`\`hospital_id\`\` is
                       automatically inherited from the actor.`
} as const;

export const Body_login_auth_login_postSchema = {
    properties: {
        grant_type: {
            anyOf: [
                {
                    type: 'string',
                    pattern: '^password$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Grant Type'
        },
        username: {
            type: 'string',
            title: 'Username'
        },
        password: {
            type: 'string',
            format: 'password',
            title: 'Password'
        },
        scope: {
            type: 'string',
            title: 'Scope',
            default: ''
        },
        client_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Client Id'
        },
        client_secret: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            format: 'password',
            title: 'Client Secret'
        }
    },
    type: 'object',
    required: ['username', 'password'],
    title: 'Body_login_auth_login_post'
} as const;

export const FLStartRoundRequestSchema = {
    properties: {
        num_rounds: {
            type: 'integer',
            maximum: 100,
            minimum: 1,
            title: 'Num Rounds',
            default: 5
        },
        min_clients: {
            type: 'integer',
            maximum: 50,
            minimum: 1,
            title: 'Min Clients',
            default: 2
        }
    },
    type: 'object',
    title: 'FLStartRoundRequest'
} as const;

export const FLStartRoundResponseSchema = {
    properties: {
        message: {
            type: 'string',
            title: 'Message'
        },
        round_id: {
            type: 'string',
            format: 'uuid',
            title: 'Round Id'
        },
        started_at: {
            type: 'string',
            format: 'date-time',
            title: 'Started At'
        }
    },
    type: 'object',
    required: ['message', 'round_id', 'started_at'],
    title: 'FLStartRoundResponse'
} as const;

export const FLStatusResponseSchema = {
    properties: {
        current_round: {
            type: 'integer',
            title: 'Current Round'
        },
        total_rounds: {
            type: 'integer',
            title: 'Total Rounds',
            default: 10
        },
        status: {
            type: 'string',
            title: 'Status',
            default: 'IN_PROGRESS'
        },
        global_accuracy: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Global Accuracy'
        },
        global_loss: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Global Loss'
        },
        participating_hospitals_count: {
            type: 'integer',
            title: 'Participating Hospitals Count',
            default: 0
        }
    },
    type: 'object',
    required: ['current_round'],
    title: 'FLStatusResponse'
} as const;

export const HTTPValidationErrorSchema = {
    properties: {
        detail: {
            items: {
                '$ref': '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Detail'
        }
    },
    type: 'object',
    title: 'HTTPValidationError'
} as const;

export const HospitalCreateSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 200,
            minLength: 2,
            title: 'Name'
        },
        license_code: {
            type: 'string',
            maxLength: 50,
            minLength: 3,
            title: 'License Code'
        },
        address: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 500
                },
                {
                    type: 'null'
                }
            ],
            title: 'Address'
        }
    },
    type: 'object',
    required: ['name', 'license_code'],
    title: 'HospitalCreate',
    description: 'Payload for creating a new hospital (Super Admin only).'
} as const;

export const HospitalResponseSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        license_code: {
            type: 'string',
            title: 'License Code'
        },
        address: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Address'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['id', 'name', 'license_code', 'address', 'is_active', 'created_at'],
    title: 'HospitalResponse',
    description: 'Safe hospital representation.'
} as const;

export const MaskTextRequestSchema = {
    properties: {
        text: {
            type: 'string',
            title: 'Text'
        }
    },
    type: 'object',
    required: ['text'],
    title: 'MaskTextRequest'
} as const;

export const MaskTextResponseSchema = {
    properties: {
        raw_text: {
            type: 'string',
            title: 'Raw Text'
        },
        masked_text: {
            type: 'string',
            title: 'Masked Text'
        },
        engine: {
            type: 'string',
            title: 'Engine'
        }
    },
    type: 'object',
    required: ['raw_text', 'masked_text', 'engine'],
    title: 'MaskTextResponse'
} as const;

export const PredictionCreateSchemaSchema = {
    properties: {
        patient_code: {
            type: 'string',
            title: 'Patient Code',
            description: 'Anonymized patient code (e.g. PAT-1042)'
        },
        age: {
            type: 'integer',
            maximum: 120,
            minimum: 0,
            title: 'Age'
        },
        gender: {
            type: 'string',
            title: 'Gender',
            description: 'Gender indicator (e.g. M, F, Other)'
        },
        blood_pressure_sys: {
            type: 'integer',
            maximum: 250,
            minimum: 50,
            title: 'Blood Pressure Sys'
        },
        blood_pressure_dia: {
            type: 'integer',
            maximum: 150,
            minimum: 30,
            title: 'Blood Pressure Dia'
        },
        cholesterol_mg_dl: {
            type: 'number',
            maximum: 600,
            minimum: 50,
            title: 'Cholesterol Mg Dl'
        },
        fasting_bs_mg_dl: {
            anyOf: [
                {
                    type: 'number',
                    maximum: 500,
                    minimum: 0
                },
                {
                    type: 'null'
                }
            ],
            title: 'Fasting Bs Mg Dl'
        },
        clinical_text_masked: {
            type: 'string',
            title: 'Clinical Text Masked',
            description: 'NER masked clinical notes'
        },
        ecg_signal_file_path: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Ecg Signal File Path',
            description: 'Local ECG signal file path'
        }
    },
    type: 'object',
    required: ['patient_code', 'age', 'gender', 'blood_pressure_sys', 'blood_pressure_dia', 'cholesterol_mg_dl', 'clinical_text_masked'],
    title: 'PredictionCreateSchema'
} as const;

export const PredictionResponseSchemaSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        patient_code: {
            type: 'string',
            title: 'Patient Code'
        },
        risk_score: {
            type: 'number',
            title: 'Risk Score'
        },
        diagnosis: {
            type: 'string',
            title: 'Diagnosis'
        },
        counterfactual_recommendations: {
            anyOf: [
                {
                    items: {
                        additionalProperties: true,
                        type: 'object'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Counterfactual Recommendations'
        },
        causal_impact: {
            anyOf: [
                {
                    additionalProperties: true,
                    type: 'object'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Causal Impact'
        },
        model_version: {
            type: 'string',
            title: 'Model Version',
            default: '1.0.0'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['id', 'patient_code', 'risk_score', 'diagnosis', 'created_at'],
    title: 'PredictionResponseSchema'
} as const;

export const RefreshTokenRequestSchema = {
    properties: {
        refresh_token: {
            type: 'string',
            title: 'Refresh Token'
        }
    },
    type: 'object',
    required: ['refresh_token'],
    title: 'RefreshTokenRequest',
    description: 'Payload for ``POST /auth/refresh``.'
} as const;

export const RoleSchema = {
    type: 'string',
    enum: ['super_admin', 'hospital_admin', 'clinician'],
    title: 'Role'
} as const;

export const TokenPairSchema = {
    properties: {
        access_token: {
            type: 'string',
            title: 'Access Token'
        },
        refresh_token: {
            type: 'string',
            title: 'Refresh Token'
        },
        token_type: {
            type: 'string',
            title: 'Token Type',
            default: 'bearer'
        }
    },
    type: 'object',
    required: ['access_token', 'refresh_token'],
    title: 'TokenPair',
    description: 'Access + refresh token response.'
} as const;

export const UserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            format: 'email',
            title: 'Email'
        },
        full_name: {
            type: 'string',
            maxLength: 120,
            minLength: 1,
            title: 'Full Name'
        },
        password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Password'
        }
    },
    type: 'object',
    required: ['email', 'full_name', 'password'],
    title: 'UserCreate',
    description: 'Payload for ``POST /auth/signup`` (public — always creates a Clinician).'
} as const;

export const UserResponseSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        email: {
            type: 'string',
            title: 'Email'
        },
        full_name: {
            type: 'string',
            title: 'Full Name'
        },
        role: {
            type: 'string',
            title: 'Role'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active'
        },
        hospital_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Hospital Id'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['id', 'email', 'full_name', 'role', 'is_active', 'hospital_id', 'created_at'],
    title: 'UserResponse',
    description: 'Safe representation of a user (no password).'
} as const;

export const ValidationErrorSchema = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        },
        input: {
            title: 'Input'
        },
        ctx: {
            type: 'object',
            title: 'Context'
        }
    },
    type: 'object',
    required: ['loc', 'msg', 'type'],
    title: 'ValidationError'
} as const;