// This file is auto-generated by @hey-api/openapi-ts

import { createClient, createConfig, type OptionsLegacyParser, urlSearchParamsBodySerializer } from '@hey-api/client-fetch';
import type { SignupAuthSignupPostData, SignupAuthSignupPostError, SignupAuthSignupPostResponse, LoginAuthLoginPostData, LoginAuthLoginPostError, LoginAuthLoginPostResponse, RefreshAuthRefreshPostData, RefreshAuthRefreshPostError, RefreshAuthRefreshPostResponse, MeAuthMeGetError, MeAuthMeGetResponse, CreateUserAsAdminUsersPostData, CreateUserAsAdminUsersPostError, CreateUserAsAdminUsersPostResponse, ListUsersUsersGetData, ListUsersUsersGetError, ListUsersUsersGetResponse, RegisterHospitalHospitalsPostData, RegisterHospitalHospitalsPostError, RegisterHospitalHospitalsPostResponse, ListHospitalsHospitalsGetData, ListHospitalsHospitalsGetError, ListHospitalsHospitalsGetResponse, CreatePredictionPredictionPredictPostData, CreatePredictionPredictionPredictPostError, CreatePredictionPredictionPredictPostResponse, GetPatientHistoryPredictionHistoryPatientIdGetData, GetPatientHistoryPredictionHistoryPatientIdGetError, GetPatientHistoryPredictionHistoryPatientIdGetResponse, MaskTextEndpointPredictionMaskTextPostData, MaskTextEndpointPredictionMaskTextPostError, MaskTextEndpointPredictionMaskTextPostResponse, FlStatusFederationStatusGetError, FlStatusFederationStatusGetResponse, FlStartRoundFederationRoundsStartPostData, FlStartRoundFederationRoundsStartPostError, FlStartRoundFederationRoundsStartPostResponse } from './types.gen';

export const client = createClient(createConfig());

/**
 * Register a new user
 */
export const signupAuthSignupPost = <ThrowOnError extends boolean = false>(options: OptionsLegacyParser<SignupAuthSignupPostData, ThrowOnError>) => {
    return (options?.client ?? client).post<SignupAuthSignupPostResponse, SignupAuthSignupPostError, ThrowOnError>({
        ...options,
        url: '/auth/signup'
    });
};

/**
 * Authenticate and receive tokens
 */
export const loginAuthLoginPost = <ThrowOnError extends boolean = false>(options: OptionsLegacyParser<LoginAuthLoginPostData, ThrowOnError>) => {
    return (options?.client ?? client).post<LoginAuthLoginPostResponse, LoginAuthLoginPostError, ThrowOnError>({
        ...options,
        ...urlSearchParamsBodySerializer,
        headers: {
            'Content-Type': 'application/x-www-form-urlencoded',
            ...options?.headers
        },
        url: '/auth/login'
    });
};

/**
 * Exchange a refresh token for a new token pair
 */
export const refreshAuthRefreshPost = <ThrowOnError extends boolean = false>(options: OptionsLegacyParser<RefreshAuthRefreshPostData, ThrowOnError>) => {
    return (options?.client ?? client).post<RefreshAuthRefreshPostResponse, RefreshAuthRefreshPostError, ThrowOnError>({
        ...options,
        url: '/auth/refresh'
    });
};

/**
 * Get current authenticated user profile
 */
export const meAuthMeGet = <ThrowOnError extends boolean = false>(options?: OptionsLegacyParser<unknown, ThrowOnError>) => {
    return (options?.client ?? client).get<MeAuthMeGetResponse, MeAuthMeGetError, ThrowOnError>({
        ...options,
        url: '/auth/me'
    });
};

/**
 * Create a user (admin only)
 * **SUPER_ADMIN** can create any role. **HOSPITAL_ADMIN** can only create **CLINICIAN** accounts.
 */
export const createUserAsAdminUsersPost = <ThrowOnError extends boolean = false>(options: OptionsLegacyParser<CreateUserAsAdminUsersPostData, ThrowOnError>) => {
    return (options?.client ?? client).post<CreateUserAsAdminUsersPostResponse, CreateUserAsAdminUsersPostError, ThrowOnError>({
        ...options,
        url: '/users/'
    });
};

/**
 * List all users (Super Admin only)
 */
export const listUsersUsersGet = <ThrowOnError extends boolean = false>(options?: OptionsLegacyParser<ListUsersUsersGetData, ThrowOnError>) => {
    return (options?.client ?? client).get<ListUsersUsersGetResponse, ListUsersUsersGetError, ThrowOnError>({
        ...options,
        url: '/users/'
    });
};

/**
 * Register a new hospital (Super Admin only)
 */
export const registerHospitalHospitalsPost = <ThrowOnError extends boolean = false>(options: OptionsLegacyParser<RegisterHospitalHospitalsPostData, ThrowOnError>) => {
    return (options?.client ?? client).post<RegisterHospitalHospitalsPostResponse, RegisterHospitalHospitalsPostError, ThrowOnError>({
        ...options,
        url: '/hospitals/'
    });
};

/**
 * List all hospitals (Super Admin only)
 */
export const listHospitalsHospitalsGet = <ThrowOnError extends boolean = false>(options?: OptionsLegacyParser<ListHospitalsHospitalsGetData, ThrowOnError>) => {
    return (options?.client ?? client).get<ListHospitalsHospitalsGetResponse, ListHospitalsHospitalsGetError, ThrowOnError>({
        ...options,
        url: '/hospitals/'
    });
};

/**
 * Ingest multimodal data and generate diagnostic prediction + XAI
 */
export const createPredictionPredictionPredictPost = <ThrowOnError extends boolean = false>(options: OptionsLegacyParser<CreatePredictionPredictionPredictPostData, ThrowOnError>) => {
    return (options?.client ?? client).post<CreatePredictionPredictionPredictPostResponse, CreatePredictionPredictionPredictPostError, ThrowOnError>({
        ...options,
        url: '/prediction/predict'
    });
};

/**
 * Get prediction history for a patient
 */
export const getPatientHistoryPredictionHistoryPatientIdGet = <ThrowOnError extends boolean = false>(options: OptionsLegacyParser<GetPatientHistoryPredictionHistoryPatientIdGetData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetPatientHistoryPredictionHistoryPatientIdGetResponse, GetPatientHistoryPredictionHistoryPatientIdGetError, ThrowOnError>({
        ...options,
        url: '/prediction/history/{patient_id}'
    });
};

/**
 * Scrub PII from clinical text notes using Member 2's spaCy NER model
 */
export const maskTextEndpointPredictionMaskTextPost = <ThrowOnError extends boolean = false>(options: OptionsLegacyParser<MaskTextEndpointPredictionMaskTextPostData, ThrowOnError>) => {
    return (options?.client ?? client).post<MaskTextEndpointPredictionMaskTextPostResponse, MaskTextEndpointPredictionMaskTextPostError, ThrowOnError>({
        ...options,
        url: '/prediction/mask-text'
    });
};

/**
 * Get current Federated Learning training status
 */
export const flStatusFederationStatusGet = <ThrowOnError extends boolean = false>(options?: OptionsLegacyParser<unknown, ThrowOnError>) => {
    return (options?.client ?? client).get<FlStatusFederationStatusGetResponse, FlStatusFederationStatusGetError, ThrowOnError>({
        ...options,
        url: '/federation/status'
    });
};

/**
 * Start a new FL training round (Super Admin only)
 */
export const flStartRoundFederationRoundsStartPost = <ThrowOnError extends boolean = false>(options: OptionsLegacyParser<FlStartRoundFederationRoundsStartPostData, ThrowOnError>) => {
    return (options?.client ?? client).post<FlStartRoundFederationRoundsStartPostResponse, FlStartRoundFederationRoundsStartPostError, ThrowOnError>({
        ...options,
        url: '/federation/rounds/start'
    });
};