// This file is auto-generated by @hey-api/openapi-ts

/**
 * Payload for ``POST /users/`` (admin-only — role is explicitly chosen).
 *
 * Role constraints enforced in the service layer:
 * - ``SUPER_ADMIN``    → can create any role; must supply ``hospital_id`` for
 * HOSPITAL_ADMIN and CLINICIAN.
 * - ``HOSPITAL_ADMIN`` → can only create ``CLINICIAN``; ``hospital_id`` is
 * automatically inherited from the actor.
 */
export type AdminUserCreate = {
    email: string;
    full_name: string;
    password: string;
    role: Role;
    hospital_id?: (string | null);
};

export type Body_login_auth_login_post = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type FLStartRoundRequest = {
    num_rounds?: number;
    min_clients?: number;
};

export type FLStartRoundResponse = {
    message: string;
    round_id: string;
    started_at: string;
};

export type FLStatusResponse = {
    current_round: number;
    total_rounds?: number;
    status?: string;
    global_accuracy?: (number | null);
    global_loss?: (number | null);
    participating_hospitals_count?: number;
};

/**
 * Payload for creating a new hospital (Super Admin only).
 */
export type HospitalCreate = {
    name: string;
    license_code: string;
    address?: (string | null);
};

/**
 * Safe hospital representation.
 */
export type HospitalResponse = {
    id: string;
    name: string;
    license_code: string;
    address: (string | null);
    is_active: boolean;
    created_at: string;
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type MaskTextRequest = {
    text: string;
};

export type MaskTextResponse = {
    raw_text: string;
    masked_text: string;
    engine: string;
};

export type PredictionCreateSchema = {
    /**
     * Anonymized patient code (e.g. PAT-1042)
     */
    patient_code: string;
    age: number;
    /**
     * Gender indicator (e.g. M, F, Other)
     */
    gender: string;
    blood_pressure_sys: number;
    blood_pressure_dia: number;
    cholesterol_mg_dl: number;
    fasting_bs_mg_dl?: (number | null);
    /**
     * NER masked clinical notes
     */
    clinical_text_masked: string;
    /**
     * Local ECG signal file path
     */
    ecg_signal_file_path?: (string | null);
};

export type PredictionResponseSchema = {
    id: string;
    patient_code: string;
    risk_score: number;
    diagnosis: string;
    counterfactual_recommendations?: (Array<{
    [key: string]: unknown;
}> | null);
    causal_impact?: ({
    [key: string]: unknown;
} | null);
    model_version?: string;
    created_at: string;
};

/**
 * Payload for ``POST /auth/refresh``.
 */
export type RefreshTokenRequest = {
    refresh_token: string;
};

export type Role = 'super_admin' | 'hospital_admin' | 'clinician';

/**
 * Access + refresh token response.
 */
export type TokenPair = {
    access_token: string;
    refresh_token: string;
    token_type?: string;
};

/**
 * Payload for ``POST /auth/signup`` (public — always creates a Clinician).
 */
export type UserCreate = {
    email: string;
    full_name: string;
    password: string;
};

/**
 * Safe representation of a user (no password).
 */
export type UserResponse = {
    id: string;
    email: string;
    full_name: string;
    role: string;
    is_active: boolean;
    hospital_id: (string | null);
    created_at: string;
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
    input?: unknown;
    ctx?: {
        [key: string]: unknown;
    };
};

export type SignupAuthSignupPostData = {
    body: UserCreate;
};

export type SignupAuthSignupPostResponse = (UserResponse);

export type SignupAuthSignupPostError = (HTTPValidationError);

export type LoginAuthLoginPostData = {
    body: Body_login_auth_login_post;
};

export type LoginAuthLoginPostResponse = (TokenPair);

export type LoginAuthLoginPostError = (HTTPValidationError);

export type RefreshAuthRefreshPostData = {
    body: RefreshTokenRequest;
};

export type RefreshAuthRefreshPostResponse = (TokenPair);

export type RefreshAuthRefreshPostError = (HTTPValidationError);

export type MeAuthMeGetResponse = (UserResponse);

export type MeAuthMeGetError = unknown;

export type CreateUserAsAdminUsersPostData = {
    body: AdminUserCreate;
};

export type CreateUserAsAdminUsersPostResponse = (UserResponse);

export type CreateUserAsAdminUsersPostError = (HTTPValidationError);

export type ListUsersUsersGetData = {
    query?: {
        limit?: number;
        skip?: number;
    };
};

export type ListUsersUsersGetResponse = (Array<UserResponse>);

export type ListUsersUsersGetError = (HTTPValidationError);

export type RegisterHospitalHospitalsPostData = {
    body: HospitalCreate;
};

export type RegisterHospitalHospitalsPostResponse = (HospitalResponse);

export type RegisterHospitalHospitalsPostError = (HTTPValidationError);

export type ListHospitalsHospitalsGetData = {
    query?: {
        limit?: number;
        skip?: number;
    };
};

export type ListHospitalsHospitalsGetResponse = (Array<HospitalResponse>);

export type ListHospitalsHospitalsGetError = (HTTPValidationError);

export type CreatePredictionPredictionPredictPostData = {
    body: PredictionCreateSchema;
};

export type CreatePredictionPredictionPredictPostResponse = (PredictionResponseSchema);

export type CreatePredictionPredictionPredictPostError = (HTTPValidationError);

export type GetPatientHistoryPredictionHistoryPatientIdGetData = {
    path: {
        patient_id: string;
    };
};

export type GetPatientHistoryPredictionHistoryPatientIdGetResponse = (Array<PredictionResponseSchema>);

export type GetPatientHistoryPredictionHistoryPatientIdGetError = (HTTPValidationError);

export type MaskTextEndpointPredictionMaskTextPostData = {
    body: MaskTextRequest;
};

export type MaskTextEndpointPredictionMaskTextPostResponse = (MaskTextResponse);

export type MaskTextEndpointPredictionMaskTextPostError = (HTTPValidationError);

export type FlStatusFederationStatusGetResponse = (FLStatusResponse);

export type FlStatusFederationStatusGetError = unknown;

export type FlStartRoundFederationRoundsStartPostData = {
    body: FLStartRoundRequest;
};

export type FlStartRoundFederationRoundsStartPostResponse = (FLStartRoundResponse);

export type FlStartRoundFederationRoundsStartPostError = (HTTPValidationError);