"""Add core database models

Revision ID: 57f9914b23c5
Revises: b418ab51599a
Create Date: 2026-08-03 17:23:42.868758

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "57f9914b23c5"
down_revision: str | Sequence[str] | None = "b418ab51599a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "fl_rounds",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("round_number", sa.Integer(), nullable=False),
        sa.Column("global_accuracy", sa.Float(), nullable=True),
        sa.Column("global_loss", sa.Float(), nullable=True),
        sa.Column("weights_path", sa.String(), nullable=True),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("fl_rounds", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_fl_rounds_round_number"), ["round_number"], unique=True
        )

    op.create_table(
        "fl_model_updates",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("fl_round_id", sa.Uuid(), nullable=False),
        sa.Column("hospital_id", sa.Uuid(), nullable=False),
        sa.Column("samples_count", sa.Integer(), nullable=False),
        sa.Column("local_loss", sa.Float(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(["fl_round_id"], ["fl_rounds.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["hospital_id"], ["hospitals.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "patients",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("patient_code", sa.String(), nullable=False),
        sa.Column("age", sa.Integer(), nullable=False),
        sa.Column("gender", sa.String(), nullable=False),
        sa.Column("hospital_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(["hospital_id"], ["hospitals.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("patients", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_patients_patient_code"), ["patient_code"], unique=True
        )

    op.create_table(
        "clinical_records",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("patient_id", sa.Uuid(), nullable=False),
        sa.Column("masked_text", sa.Text(), nullable=False),
        sa.Column("symptoms", sa.JSON(), nullable=True),
        sa.Column("blood_pressure_sys", sa.Integer(), nullable=True),
        sa.Column("blood_pressure_dia", sa.Integer(), nullable=True),
        sa.Column("cholesterol_mg_dl", sa.Float(), nullable=True),
        sa.Column("fasting_bs_mg_dl", sa.Float(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(["patient_id"], ["patients.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("clinical_records", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_clinical_records_patient_id"), ["patient_id"], unique=False
        )

    op.create_table(
        "ecg_records",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("patient_id", sa.Uuid(), nullable=False),
        sa.Column("signal_file_path", sa.String(), nullable=False),
        sa.Column("sampling_rate_hz", sa.Integer(), nullable=False),
        sa.Column("lead_count", sa.Integer(), nullable=False),
        sa.Column("duration_seconds", sa.Float(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(["patient_id"], ["patients.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("ecg_records", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_ecg_records_patient_id"), ["patient_id"], unique=False
        )

    op.create_table(
        "predictions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("patient_id", sa.Uuid(), nullable=False),
        sa.Column("risk_score", sa.Float(), nullable=False),
        sa.Column("diagnosis", sa.String(), nullable=False),
        sa.Column("xai_counterfactuals", sa.JSON(), nullable=True),
        sa.Column("causal_impact", sa.JSON(), nullable=True),
        sa.Column("model_version", sa.String(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(["patient_id"], ["patients.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("predictions", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_predictions_patient_id"), ["patient_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("predictions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_predictions_patient_id"))

    op.drop_table("predictions")
    with op.batch_alter_table("ecg_records", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_ecg_records_patient_id"))

    op.drop_table("ecg_records")
    with op.batch_alter_table("clinical_records", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_clinical_records_patient_id"))

    op.drop_table("clinical_records")
    with op.batch_alter_table("patients", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_patients_patient_code"))

    op.drop_table("patients")
    op.drop_table("fl_model_updates")
    with op.batch_alter_table("fl_rounds", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_fl_rounds_round_number"))

    op.drop_table("fl_rounds")
    # ### end Alembic commands ###
